# Generated by Django 3.1.2 on 2021-02-19 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_place_information_end_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='txtFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to='allTxtFiles')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 2, 19, 3, 51, 5, 862528))),
            ],
        ),
        migrations.DeleteModel(
            name='place_information',
        ),
    ]
